### ISSUE TITLE
Remove `/` from `entityMap.escape`.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1189]
Similar to #615 `_.escape` doesn't need to worry about '/'.

**Comment by mitar** [comment]
What? `/` should be escaped? I opened #2650 to fix that, but now it has been closed with a link to this issue. What reason is that?

> Characters like > and / don't require escaping in HTML and have no special meaning unless they're part of a tag or an unquoted attribute value (there are no tags as they escaped).

`>` and `/` have a meaning. The are special characters and could be lead to tricky situations. We should not try to be too smart here, it does not really work well for security.

For example, do you know that the following is a valid HTML 4 snippet?

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title/hello/
<body>
<p/hello/
```

See how `/` have special meaning?

**Comment by mitar** [comment]
Also, in meantime, it seems that underscore is escaping `>` again. Could we start escaping `\` as well again?

**Comment by mitar** [comment]
I think that conversation is invalid. Nobody here made any serious computer security argument. Just saying that "because I do not know how this could be exploited" is not an argument why this should not be done.

**Comment by mitar** [comment]
> Why all those characters, instead of just the ones the HTML spec defined after careful research of existing behavior? It seems no one knows, and there are no examples either.

Because there are multiple HTML specs you have to care about. Not just the latest one. And multiple browser implementations. Not just Chrome, Firefox, and IE. Libraries as general as this one can be used in so many contexts. Do you really know of all parser engines somebody implemented? Various browser implementations for accessibility, and how they convert bad HTML into something they operate on?

**Comment by jdalton** [comment]
@mitar The escape/unescape methods aren't intended to be a full-on robust solution. It hits the high notes. You might check out [he (HTML entities)](https://www.npmjs.com/package/he) instead of spamming a 3 yrs old thread.

**Comment by mitar** [comment]
> The escape/unescape methods aren't intended to be a full-on robust solution.

But they could be by adding one more character. You are like almost there.

I am spamming this thread because it was mention as an argument why #2650 is closed. And by reading through comments here I was not convinced by them.

**Comment by jdalton** [comment]
> But they could be by adding one more character. You are like almost there.

Naw, it's way more complicated than that.

> And by reading through comments here I was not convinced by them.

You don't have to be.

**Comment by mitar** [comment]
Exactly, and this is why I made arguments for inclusion. You have not even addressed them above. Just saying that you do not want to be a comprehensive solution is not an argument why you would not add one more character which would solve the problem. Alternatively, if this is really a stance, I would suggest updating documentation explaining that it is not a comprehensive and robust solution and that one should in that case use another package.

The issue is that people might trust that underscore is behaving based on current security best practices, and it is not. So we should warn developers that this is the case so that they can make an informative choice.

> Naw, it's way more complicated than that.

How is more complicated than chaning escaping and unescaping?

**Comment by jdalton** [comment]
> Alternatively, if this is really a stance, I would suggest updating documentation explaining that it is not a comprehensive and robust solution and that one should in that case use another package.

The documentation is up-front about the handful of characters it escapes.

> How is more complicated than changing escaping and unescaping?

Take a look at [the source of  he (HTML entities)](https://github.com/mathiasbynens/he).

**Comment by mathiasbynens** [comment]
> For example, do you know that the following is a valid HTML 4 snippet?
> 
> ```
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
>   "http://www.w3.org/TR/html4/strict.dtd">
> <html>
> <head>
> <title/hello/
> <body>
> <p/hello/
> ```
> 
> See how `/` have special meaning?

 @mitar [I know](https://mathiasbynens.be/notes/minimal-html#4.0-strict), but I also know that this is/was only true in theory. No browser ever implemented such SGML-style parsing.

**Comment by mitar** [comment]
> Take a look at the source of he (HTML entities).

I think that library does more than escaping, it also does entity encoding, if you want that. Here, for the purposes of underscore, I think we talk about security-based escaping. For that, [map here](https://github.com/mathiasbynens/he/blob/master/he.js#L35) is the same as underscore's, without a `/` escaped. So that library is in fact not more secure than underscore.

> That said, I do have a note on my version.

Oh, that is great! But maybe add also a link to OWASP mentioning that OWASP disagrees with this shorter list and recommends a longer one. Because he library does not seem to be a "more secure" version of the escaping, just a library to encode everything into HTML entities, probably mostly if you want unicode to be represented well in ASCII. ASCII does not mean secure HTML.

> No browser ever implemented such SGML-style parsing.

The issue is that you do not know that. You think only about popular user agents. What about bots? What about readers for accessibility? What about various e-readers?

I really like the initial comment by @jashkenas:

> I'm not certain that it doesn't, and when it comes to HTML escaping, we'll err on the safe safe.

Anyway, I raised the point. I made a pull request. I did my part. The rest is on others.

**Comment by mitar** [comment]
@mathiasbynens, why don't you contribute to OWASP wiki and get them to fix this and remove `/`?

**Comment by mathiasbynens** [comment]
Let’s be clear here: if you inject user-supplied content `<p$HERE` (even after running it through `_.escape`) you have much bigger problems than just `/`. 😨

----

> The issue is that you do not know that. You think only about popular user agents.

What makes you say that? Are you a mind reader?

HTML was originally defined on top of SGML but it was never (to my knowledge) implemented as such. That’s [one of the main things “HTML5” rectified](https://blog.whatwg.org/html-vs-xhtml) — this would’ve been impossible if any Web content relied on such constructs, which would inevitably have happened if some user agent supported it.

> What about bots?

Is there a crawler bot that implements SGML parsing rules? It would have trouble parsing lots of web pages. How would one trigger XSS in a bot, exactly? Why should I care about my web page triggering XSS in someone else’s crappy bot?

> What about readers for accessibility?

Why are you special-casing accessibility readers? As far as I know they just build on top of the existing browser DOM rather than implementing their own browser / HTML parser etc.

> What about various e-readers?

Can you give an example? I have no idea what you mean by “e-reader”.

Please provide actual counter-examples (i.e. any browser-like piece of software that supports SGML-style parsing) if you have any. Pretending to have mind-reading abilities, naming random vague things, and shifting the burden of proof to others is not helpful.

**Comment by mitar** [comment]
I agree. I do not know of such cases. This is why I am using hypothetical examples. Because we cannot really know about such implementations. It is true that there is a little probability there is such. It is also true that we might not want to care about those anyway. But it is also true that it is a good practice to escape special symbols. But there could be exceptions to this good practice.

I would love if the experts could get make a final list of those symbols. If OWASP could have that list. If it is so clear that `/` is not needed, why is it then listed there?

**Comment by jdalton** [comment]
> I would love if the experts could get make a final list of those symbols.

IIFC we took input from XSS enthusiast folks, like [0x6D6172696F](https://twitter.com/0x6D6172696F), at the time. We've already dug into the history of the OWASP characters earlier in the thread.
