### ISSUE TITLE
_.zip'ing different length arrays.

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/underscore#1237]
Zip functions take in arrays, and give you back tuples of values from each array, grouped by index.

What to do when the incoming arrays have different lengths is done differently in different languages and libraries. It's recently been brought to my attention by Jesse Pollak that:
- Python and Haskell will only return tuples for indexes where all lists have values (the minimum length), and discard the unmatching values.
- F# will throw an error if you try to zip differently-length'd arrays.
- Ruby will use the length of the first array you zip, discarding values or padding the others with `null` to fit.
- Underscore will try not to destroy any data, and will use the _maximum_ length of the incoming arrays.

(I think we may have talked about this before.)

Which behavior is best?

**Comment by OliverJAsh** [comment]
This issue is old, but I think there's a flaw in this argument, so this may be worth reconsidering.

> you can always stop iterating when you see undefined values, or compact out undefined parts of your result.

I don't think this will work if you're zipping an arrays which intentionally have `undefined` values. How would you distinguish `undefined` values that come from the source array versus ones that are due to `zip`s current behaviour? E.g.

``` js
const xs [1, undefined, 2];
const ys = [1, 2];
zip(xs, ys) // => [[1, 1], [undefined, 2], [2, undefined]]
```
