### ISSUE TITLE
_.sortedIndex align with _.sortBy

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1834]
``` js
_.sortBy([undefined, 1, undefined, 2]);
// => [1, 2, undefined, undefined]
_.sortedIndex([1, 2, undefined, undefined], undefined);
// => 0; though should be 2
```

**Comment by arianf** [comment]
@megawac I believe I have a solution to this problem, that would work in all cases, but it changes the function around just a bit... 

```javascript
_.sortedIndex([1, 2, undefined, undefined], undefined);
// => 2
```

but the draw back to my solution is that for duplicate values in an array, it will give you the last index :

```javascript
_.sortedIndex([10, 20, 30, 40, 50], 30);
// => 3
```
it basically gives you https://github.com/jashkenas/underscore/issues/1882 but to my defense, the definition of the function in the docs still holds true:

>Uses a binary search to determine the index at which the value should be inserted into the list in order to maintain the list's sorted order. If an iteratee function is provided, it will be used to compute the sort ranking of each value, including the value you pass. The iteratee may also be the string name of the property to sort by (eg. length).

Which does insert it into the list **in order to maintain the list's sorted order**. What do you think?

**Comment by megawac** [comment]
If you would like to share a gist @arianf I would be interested in seeing
it, even if it may not be suitable

**Comment by arianf** [comment]
This is my old solution: https://gist.github.com/arianf/926c79e57d1779408cc9#file-orignal-solution-to-_-sortedindex

I've updated my solution to work the original way for duplicate values, I am about to make a pull request.

**Comment by amZotti** [comment]
:+1: Great work @arianf
