### ISSUE TITLE
Feature request: _.isUndeclared

### ISSUE THREAD

**Issue by thure** [jashkenas/underscore#2015]
Would there be any interest in an `_.isUndeclared` function? `_.isUndefined` doesn't cut it (for me) because it throws a `ReferenceError` if its argument is undeclared.

I've needed this before inside underscore templates. Happy to make a pull request with this function.

**Comment by michaelficarra** [comment]
I'd love to see this PR.

**Comment by thure** [comment]
It would pretty much just look like:

    _.isUndeclared = function(obj) {
      return typeof obj === "undefined";
    };

In this form, it could be used in [L48](https://github.com/jashkenas/underscore/blob/master/underscore.js#L48) and [L49](https://github.com/jashkenas/underscore/blob/master/underscore.js#L49).

Alternatively, this definition could replace `_.isUndefined`, but that could be controversial since the perf of `obj === void 0` is [not always the same as `typeof obj === "undefined"`](http://jsperf.com/typeof-vs-undefined-check/5).

Thoughts?

**Comment by akre54** [comment]
`typeof` is guaranteed to be safe in handling `ReferenceError`s, while functions aren't.

Unfortunately, and what @michaelficarra was getting at (albeit a bit snidely) is that this isn't possible. Javascript just doesn't have a nice way&mdash;outside of `typeof`&mdash;for this check. Try using the `variable` parameter in `_.template` instead of relying on the `with` if you need this.

**Comment by thure** [comment]
TIL

**Comment by michaelficarra** [comment]
Hey, you never know – I'm always hoping to learn something new. Anyways, on a related not, as of ES6 even `typeof` won't protect us from ReferenceErrors in block-scoped variables' temporal dead zone. That was one of the few things we could actually rely on in this language!

**Comment by jdalton** [comment]
Related https://twitter.com/kangax/status/553631599368339457.

**Comment by akre54** [comment]
> as of ES6 even typeof won't protect us from ReferenceErrors in block-scoped variables' 

Let's not spread FUD. The typeof undefined check is mostly (only?) useful when trying to search for free variables (`exports`, `global`/`window`, `ArrayBuffer`, etc). As brought up in the linked thread `let` is only used for user-defined vars, where this really shouldn't be a concern. 

Back to Underscore, is there a reason we shouldn't make the `with` behavior opt-in instead of opt-out?

**Comment by lukeasrodgers** [comment]
@thure, out of curiousity, in what cases would a `typeof` not suffice for you?

**Comment by megawac** [comment]
https://twitter.com/kangax/status/553631599368339457?s=09
