### ISSUE TITLE
No proper documentation of predicates

### ISSUE THREAD

**Issue by PhiLhoSoft** [jashkenas/underscore#2052]
When I look at the description of the find() function, the first one mentioning a predicate function as parameter (in the home page reference), I don't see a description of the predicate parameters. There is only an example with the value as argument. I discovered in a Stackoverflow comment that it can accept more arguments, something confirmed by looking at the source code...

I suggest to detail these parameters, like it is done for the iteratee function in the each() function description.

Note that reduceRight doesn't have a proper description of iteratee, too, so I suggest to inspect each description and supply additional information.

Thanks.

**Comment by jashkenas** [comment]
Thanks, but I don't think these changes would be an improvement to the docs.

**Comment by captbaritone** [comment]
I'd like to +1 this, despite the fact that it's already been marked "wontfix".

The predicate argument contains quite a bit of powerful magic which is never explicitly documented. My companies code is littered with lines like:

    _.where(options, function(option) { return option.selected == true; });
    _.any(tagNames, function(name) { return name == 'featured'; });

And it's been an uphill battle showing everyone that these would be better written as:

    _.where(options, {selected: true});
    _.any(tagNames, 'featured');

I only know to suggest these because I chose to take a slow evening and read through Underscore's entire source code (an enjoyable evening I must say!). Where should I direct someone if I wanted to show them this functionality? Currently I send them a link like this: https://github.com/jashkenas/underscore/blob/master/underscore.js#L86-L94 which seems awkward.

**Comment by akre54** [comment]
Are you perhaps looking for http://underscorejs.org/#iteratee?

**Comment by Florian-R** [comment]
There's some inconsistency in the signature of the methods accepting an iteratee as a predicate. From the doc

> _.find(list, predicate, [context])

vs 


> _.max(list, [iteratee], [context])

Maybe this could be harmonized to better reflect than predicate is an iteratee.
On an other hand, as a non-english native speaker, I’m not sure this is correct, nor understandable to says : 

 > Returns the key where the **iteratee** truth test passes

**Comment by captbaritone** [comment]
@akre54 I suppose I was :smile: Thanks.

**Comment by akre54** [comment]
@Florian-R  Sure, got a suggestion of how to make those a little more consistent?

The second part seems pretty clear to me, is there something you think is missing?

**Comment by Florian-R** [comment]
Not really sure about this, but maybe we could just add a link to http://underscorejs.org/#iteratee on each occurrence of predicate?

**Comment by captbaritone** [comment]
I like the idea of a link. It seems reasonable that one could learn about the behavior of a function just by reading (and following the links of) that specific function.
