### ISSUE TITLE
Discuss latest changes to master before releasing

### ISSUE THREAD

**Issue by thejameskyle** [jashkenas/underscore#2061]
There are a lot of changes happening right now that have not been discussed, including breaking changes.

https://github.com/jashkenas/underscore/compare/6d3100ed758818ba41cde2dc178524e24f236b23...master

At the very least these should be pull requests that other contributors can discuss.

Changes include:
- Removing `_.transform`
- Removing `_.create`
- Renaming `_.keysIn` to `_.allKeys`
- Renaming `_.mapValues` to `_.mapObject`
- Renaming `_.assign` to `_.extendOwn`
- Renaming `_.matches` to `_.isMatch`
- Adding `_.matcher` alias `_.matches`
- Reverted some changes in 1.7 (ie. `_.extend`)

**Comment by thejameskyle** [comment]
Well, too late I guess https://twitter.com/jashkenas/status/568564455937839106

**Comment by jashkenas** [comment]
Too late indeed. We can follow up with a 1.8.1 pronto if needed. Hopefully it won't be...

**Comment by jridgewell** [comment]
> Renaming _.matches to _.isMatch
> Adding _.matcher alias _.matches

Those were both fixed. 1.7's `_.matches` is 1.8's `_.matcher = _.matches`. 1.8's `_.isMatch` is what you expect it is.

**Comment by jridgewell** [comment]
> Reverted some changes in 1.7 (ie. _.extend)

1.8 has the same behavior as 1.6, which is [intentional](https://github.com/jashkenas/underscore/pull/1799#issuecomment-53581153) https://github.com/jashkenas/underscore/commit/b17bd671ca49e1b76b43f29cee40352fb4651c9f.

**Comment by jridgewell** [comment]
Do you mind cleaning up the ones that weren't changes made last minute by @jashkenas? `_.matches`, `_.matcher`, `_.isMatch`, and `_.extend` undiscussed issues.

I'd love for this to be the jumping off point to fix 1.8 with 1.8.1. And this time, let's [actually](https://github.com/jashkenas/underscore/issues/1855) fix it.

**Comment by jridgewell** [comment]
Additionally, we have a breaking change to a brand new feature in 1.7: Overriding `_.iteratee` no longer changes the behavior of the collection iterators. Fix is https://github.com/jashkenas/underscore/pull/1965.

@jashkenas Please revoke 1.8 from npm. Let's get these issues worked out, and ship a 1.8.1.

**Comment by jashkenas** [comment]
I don't think we should allow overriding `iteratee`. It's not a very pleasant API — so that change is alright.

I'm more concerned about the IE8 test failures. What on earth happened to poor old IE?

**Comment by jridgewell** [comment]
> I don't think we should allow overriding iteratee. It's not a very pleasant API — so that change is alright.

But https://github.com/jashkenas/underscore/pull/1582... and it was brand new!

**Comment by jridgewell** [comment]
Adding to this:

- [ ] IE non-enumerable property support has been [removed](https://github.com/jashkenas/underscore/commit/5350a2ff3e362757f384c7c0096f24ad68c38fd0) in 1.8.1
- [ ] Edge case tests were [removed](https://github.com/jashkenas/underscore/commit/ef3164fcad059434a95f0eb5ad48dba1999a5b62) in 1.8.1

**Comment by TheSpiderPig** [comment]
Guys USE SEMVER! These sort of breaking changes should make this pump up a complete version number!

**Comment by jridgewell** [comment]
Closing this since there are relevant PRs for each of the changes.

- Removing _.transform
  - https://github.com/jashkenas/underscore/pull/2075
- Removing _.create
  - https://github.com/jashkenas/underscore/pull/2074
- Renaming _.keysIn to _.allKeys
  - https://github.com/jashkenas/underscore/pull/2071
- Renaming _.mapValues to _.mapObject
  - https://github.com/jashkenas/underscore/pull/2073
- Renaming _.assign to _.extendOwn
  - https://github.com/jashkenas/underscore/pull/2070
- Renaming _.matches to _.isMatch
  - https://github.com/jashkenas/underscore/pull/2057
- Adding _.matcher alias _.matches
  - https://github.com/jashkenas/underscore/pull/2057
- Reverted some changes in 1.7 (ie. _.extend)
  - [Non issue](https://github.com/jashkenas/underscore/pull/1799#issuecomment-53581153), https://github.com/jashkenas/underscore/commit/b17bd671ca49e1b76b43f29cee40352fb4651c9f
