### ISSUE TITLE
Sauce Labs testing of pull requests?

### ISSUE THREAD

**Issue by cvrebert** [jashkenas/underscore#2085]
Related to #2059, I'm wondering if there'd be any interest in running Sauce Labs real-browser JS tests on pull requests too? Over at [Bootstrap](https://github.com/twbs/bootstrap), we're using [Savage](https://github.com/twbs/savage) to accomplish this. (To see it in action, look at https://github.com/twbs-savage?tab=activity)
If there's interest, I'd be happy to help with the setup of a Savage instance for Underscore.

**Comment by megawac** [comment]
Pinged you on gitter @cvrebert

**Comment by cvrebert** [comment]
(Responded & had positive-sounding conversation on gitter.)

**Comment by jdalton** [comment]
It seems like a lot of complexity for little gain as the cross browser issues are pretty well known in Underscore.

**Comment by jgonggrijp** [comment]
This may or may not become interesting again after #2847.

**Comment by jgonggrijp** [comment]
It's interesting again, because the Sauce Labs tests are now running, but some browsers fail to spin up. This is causing the Travis build to report as broken overall, even though all the tests are passing. [This line](https://travis-ci.org/github/jashkenas/underscore/jobs/730261946#L804) is a good example: passing tests above it, failing Sauce Labs browsers below it.
