### ISSUE TITLE
templateSettings is not inherited

### ISSUE THREAD

**Issue by otakustay** [jashkenas/underscore#2098]
In some complex case we want to extend `underscore` but not mix methods on it, so we create a "inherited" instance of it:

```javascript
var util = Object.create(_);

util.myExtensionMethod = ...
```

In this case, setting `templateSettings` on `util` takes no effect:

```javascript
util.templateSettings = {
    interpolate: /\$\{(.+?)\}/g // ${foo}
};

var str = util.template('${x}', {x: 1});
console.log(str); // outputs "${x}", not "1"
```

I know it may be by design, but it actually a confusion to developers use the inherited way, we must override `template` method like:

```
var TEMPLATE_SETTINGS = {...};

util.template = function (text, data) {
    return _.template(text, data, TEMPLATE_SETTINGS);
};
```

which is not that straight forward

**Comment by d10** [comment]
This is because Underscore refers to the `_.templateSettings` object explicitly. See [here](https://github.com/jashkenas/underscore/blob/master/underscore.js#L1414).

**Comment by otakustay** [comment]
Yes the reason is quite explicit, I'm just wondering if it should be `this.templateSettings`, if so I can create a pull request for this

**Comment by akre54** [comment]
Is there any reason you can't just use `_.noConflict()` for your use case?

Underscore really isn't meant to be cloned in this way, and there are [many](https://github.com/jashkenas/underscore/blob/1.8.2/underscore.js#L87-L92), [many](https://github.com/jashkenas/underscore/blob/1.8.2/underscore.js#L148) [places](https://github.com/jashkenas/underscore/blob/1.8.2/underscore.js#L1037-L1045) that refer to the internal `_` object instead of your cloned instance.

**Comment by otakustay** [comment]
This is a different case, we are not mean to release the `_` variable, but require multiple instances of `underscore` object.

We are developing a plugin based app, in this app each plugin may (or may not) extend `underscore` object, add some methods on it, in order to prevent these methods conflict with each other, we need to create multiple `underscore` objects with inheritance and isolate them in every plugin.

After all, if this (singleton) is a design goal of underscore, I may resolve it myself and close this issue :)
