### ISSUE TITLE
[Bug] Underscore in combination with jQuery load()

### ISSUE THREAD

**Issue by paulness** [jashkenas/underscore#2131]
Hi when loading an external page that has underscore, using jQuery load. The entire page goes blank and all that remains is the underscore script declaration..

Any ideas on what needs to be fixed?

https://api.jquery.com/load/
<script src="http://underscorejs.org/underscore.js"></script>

**Comment by akre54** [comment]
Hi @paulness, would you mind creating a gist or jsfiddle demonstrating the problem? It's hard to tell without a test case.

**Comment by paulness** [comment]
Hi Akre54,

I realized that it is the 'conditional loading' of underscore causing the problem. Here is the GIST, not sure on the solution as of yet. You may need to Allow-Origin * on your local webserver for this to work in your browser *

https://gist.github.com/paulness/829e9678d1e922248ef8

**Comment by akre54** [comment]
This doesn't look like an Underscore problem. Try the mailing list, StackOverflow, or the gitter room. 

That said, I noticed a few issues that might be causing your problem. Why are you using document.write instead of a script tag? Just load Underscore using a regular script tag and you should be fine.

You also shouldn't be using the version of Underscore from underscorejs.org. Use `//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.2/underscore-min.js` instead. Can you give those a try and let me know if that fixes it for you? If it doesn't, try one of the above mentioned places.
