### ISSUE TITLE
adding argument checker funciton

### ISSUE THREAD

**Issue by yonatanmn** [jashkenas/underscore#2216]
Hi, 
take a look at [this](https://github.com/yonatanmn/DataTypes-and-arguments-checker),
What do you think about adding similar functionality to undesrscore (as a `_.check`, not `Function.prototype`)? 
I believe this could be extremely useful, and worth thinking about. 

I haven't contributed to this library yet, but if you think this is a good idea I can try adding a pull request.

**Comment by jridgewell** [comment]
I see this having a ton of edge cases and customization, and is better left for a specialized library. We've also been against type checking in the [past](https://github.com/jashkenas/underscore/pull/1968#issuecomment-66702438) since JS is an inherently dynamic language.

Thanks for bringing it up, though!
