### ISSUE TITLE
isString is hard to find/read

### ISSUE THREAD

**Issue by generateui** [jashkenas/underscore#2271]
While

    // Add some isType methods: isArguments, isFunction, isString, isNumber, isDate, isRegExp, isError.
    _.each(['Arguments', 'Function', 'String', 'Number', 'Date', 'RegExp', 'Error'], function(name) {
      _['is' + name] = function(obj) {
        return toString.call(obj) === '[object ' + name + ']';
      };
    });

is terse, it is not very useful in finding code. A simple ctrl+f on isString does not work.

I suggest explicit function declaration and implementation to make it 1) more readable and 2) more findable and 3) better toolable.

**Comment by michaelficarra** [comment]
Ctrl+f on isString does indeed find that line, that's why they're all listed there. I think the current implementation is fine. If what you're trying to express is that all of these functions have an identical structure in their implementation, this is more readable than having separate implementations.
