### ISSUE TITLE
_.isNumber( NaN ) == true

### ISSUE THREAD

**Issue by judsonbsilva** [jashkenas/underscore#2304]
Why `_.isNumber( NaN ) == true` ?

**Comment by jdalton** [comment]
Hi @judsonbsilva! 

`_.isNumber( NaN )` is `true` because `NaN` is classified as a number just as `Infinity` and `-Infinity` are.

The `_.isNumber` method is not intended for numeric validation just as `_.isDate` will not validate whether you date object is valid `new Date(Infinity)`.

If you're looking for validation there's `_.isFinite` or ES6 `Number.isFinite`, `Number.isNaN`, `Number.isInteger`, and `Number.isSafeInteger`.

**Comment by judsonbsilva** [comment]
:) Ohh... nice, thank's

**Comment by bjmiller** [comment]
Can this explanation go in the documentation?  We get this question in some form quite frequently.
