### ISSUE TITLE
_.range(-10) auto `step` of `-1`

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2364]
What do you all think about having `_.range(-10)` auto `step` of `-1`.
```js
_.range(-10);
// => [0, -1, -2, -3, -4, -5, -6, -7, -8, -9]
```

Neat or too much magic?

**Comment by nettofarah** [comment]
This looks pretty cool.

**Comment by jridgewell** [comment]
Seems like we should extend that to `_.range(0, -10)` if we do.

**Comment by megawac** [comment]
Seems neat, although something not present in other range implementations (such as python range). I would be okay with this if users were to start requesting/ :+1:ing it. Personally, I'm +0 for it

**Comment by jdalton** [comment]
This was inspired by https://github.com/abozhilov/ES-Iter#iterrangeend.

**Comment by jdalton** [comment]
@jridgewell
> Seems like we should extend that to `_.range(0, -10)` if we do.

I can dig.

**Comment by jashkenas** [comment]
Seems like a good idea to me.

**Comment by jdalton** [comment]
Rock! Over on the es-discuss side of things there's talk of potentially standardizing a `range` function and they're looking at libs like Underscore for guidance. If you have usage data that would help.

**Comment by jashkenas** [comment]
I don't have data, but this is an even more interesting problem over on the CoffeeScript side of things where we don't have a runtime.

So we can do automatic stepping of -1 for ranges like `for x in `[10..-1]`

But we can't do automatic negative stepping for ranges like `for x in [b..a]`, where the values aren't known at compile time.

**Comment by jdalton** [comment]
More related discussion over at https://github.com/abozhilov/ES-Iter/issues/8#issuecomment-160315806.

**Comment by abozhilov** [comment]
I think the negative ranges are bad idea in first place. They brake the entire math theory about intervals. 
In formal language, left closed interval is expressed as: `[a, b) = a <= x < b`, negative ranges are not compliant with that formalization.  

Also in my opinion the ranges in programming languages must be both side closed, otherwise it tends to overflow errors.  For example if we have 8 bits unsigned numbers and I want to represent its ranges of values, then `[0..255]` is the right thing, but if that range is left closed, then I have to: `[0..(255+1)]` and it causes overflow of the type.
I hope if JS one day has separate range type, to implement it as it is in Ruby.    

Let's get back to `range()`. In my opinion this is Python's idiom which is useful to emulate C-like loops in Python. Am I wrong?

I still can't find use case of Python's `range` with negative step, even in Python. The common use case is to use `range` with combination of `reversed`. I think we should abandon negative steps in `range` at all. Instead of that, we can have something like: `rangeRight` or `reversedRange` which generates the range as it's generated by `range` but in reverse order.  

I'm open for discussion, and ES-Iter is non TC39 project. I'm trying to implement reasonable itertools for JavaScript.

**Comment by jdalton** [comment]
@abozhilov
> Instead of that, we can have something like: `rangeRight` or `reversedRange` which generates the range as it's generated by range but in reverse order.

Would the implementation of the `rangeRight` and `reversedRange` use an unexposed negative step anyways? With `step` as it is folks can compose the flavors of range they like.
```js
var rangeRight = _.partial(_, _, -1);
var rangeStrict = _.partial(_, _, 1);
```

**Comment by abozhilov** [comment]
Indeed it does. The major difference is that, `range` and `rangeRight` aways return same result but in different order. 
e.g. `range(10, 30, 6) // 10 16 22 28` `rangeRight(10, 30, 6) // 28 22 16 10`.  

Do you know an use-case for explicit negative step? Even in Python you can observe `reversed(range(10))`. I think the common use case of ranges with negative step would be to iterate arrayLike collection in reverse order and still keeping numeric indexes. If we allow negative steps we will observe code like that: `range(arr.length - 1, -1, -1)`. I think `reversedRange(arr.length)` is definitely better than that.

**Comment by jdalton** [comment]
> Do you know an use-case for explicit negative step?

Wanting an array in descending order is the case.

> Even in Python you can observe `reversed(range(10))`.

Why add an extra function call with a negative step would do?

>  I think `reversedRange(arr.length)` is definitely better than that.

Ya maybe.

**Comment by abozhilov** [comment]
>Why add an extra function call when a negative step would do?

The main point is that `reversedRange` is absolute same as `range`. With negative step is not 100% guarantee that. e.g. 

```javascript
range(0, 5, 2) // 0 2 4
reversedRange(0, 5, 2) // 4 2 0

range(5, 0, -2) // 5 3 1
``` 

I really like `reversedRange` but suddenly I saw use-case of negative step. 
Consider you want to start from the last element of array and iterate with step = 2. Then `reversedRange` is useless and you are going to use `range(arr.length - 1, -1, -2)` but I'm still not sure about this use case.

**Comment by jridgewell** [comment]
While we're talking about it, Unix's `seq` command supports auto `-1` steps:

```bash
$ seq 3
1
2
3
$ seq 0 3
1
2
3
$ seq -1
1
0
-1
$ seq 2 0
2
1
0
```

**Comment by jdalton** [comment]
I'm kicking around a `_.rangeRight` to complement `_.range` for those awkward negative step cases without removing the ability to use a negative step.

**Comment by abozhilov** [comment]
@jdalton cool! I did the same thing in ES-Iter. You can check `rangeRight` https://github.com/abozhilov/ES-Iter/blob/develop/src/Iter.js#L134
