### ISSUE TITLE
i can not find the function _.isNumber in the source code 

### ISSUE THREAD

**Issue by zzzgit** [jashkenas/underscore#2419]
i downloaded the source code on this repository,but i can not find out where the function ```_.isNumber``` is been defined.
what is the matter?

**Comment by jridgewell** [comment]
It's defined [at runtime](https://github.com/jashkenas/underscore/blob/master/underscore.js#L1288-L1293).

**Comment by akre54** [comment]
Please don't use Github issues for questions, it's very rude. Use the gitter channel, StackOverflow, or the mailing list if you have any questions.

**Comment by jdalton** [comment]
Instead of chastising folks lets just point them in a friendly direction of support with [a link to the gitter channel](https://gitter.im/jashkenas/underscore) and [stackoverflow](http://stackoverflow.com/search?q=underscore.js). I think it'd be great if we added these links to the repo's readme too.

**Comment by captbaritone** [comment]
A link to the mailing list would also be appreciated. I haven't been able to locate it myself. :crying_cat_face:

**Comment by jdalton** [comment]
As far as I know there isn't an Underscore specific mailing list. However, there is a Backbone one.
