### ISSUE TITLE
why should make a isArrayLike check first before the isArray check?

### ISSUE THREAD

**Issue by zzzgit** [jashkenas/underscore#2420]
```javascript
if (isArrayLike(value) && (_.isArray(value)){

}
```
sorry but why should make a ```isArrayLike``` check first before the ```isArray``` check?

**Comment by michaelficarra** [comment]
Are you saying this code is somewhere in underscore's source?

**Comment by captbaritone** [comment]
I found two instances of us doing things that kinda _look_ like we're doing that, but due to the parenthesis we are actually doing something else.

https://github.com/jashkenas/underscore/blob/master/underscore.js#L506
https://github.com/jashkenas/underscore/blob/master/underscore.js#L1267

In both cases we are trying to test for a sub-set of "array like" objects.

**Comment by zzzgit** [comment]
captbaritone,is it necessary to check whether it's an "array like" objects first?
i think _.isArray(value) is here is enough.
