### ISSUE TITLE
_.sortBy errors on symbols.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2501]
``` js
_.sortBy([1, Symbol()]);
// errors
```

This affects `_.max` and `_.min` too.

**Comment by jgonggrijp** [comment]
`_.sortBy` is for when you can reduce your values to a single string or number so that you can meaningfully apply the `<` operator. If you need to do something more fancy, pass your own custom comparator function to [`Array.prototype.sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) instead. Note that this function is also available in Underscore OOP notation and in chains as `_(yourArray).sort`.

Related to #2848.
