### ISSUE TITLE
`restArgs` and `rest` in Line107

### ISSUE THREAD

**Issue by hushPlease** [jashkenas/underscore#2542]
Hello Mr.Kenas
My group has been learning your underscore for a month or so.I am trying to translate your notations in the original code to Chinese, which are basically based on my comprehension , so that members among my group will be able grasp and perform more efficiently.But here comes some issues that i can't understand well.
One issue, Line 107.Original code says `restArgs` is similar to ES6's `rest` and gives a link. I understand that, sort of, but I can only paraphrase the comments, not metaphrase, which may cause great discrepancies in comprehension among users. I searched StackOverflow and didn't find any useful examples..
BTW, Underscore is under MIT license right? I have pushed [the Chinese version](https://github.com/hushPlease/underscore-Chinese-comment-Edition) to my github. No commercial use, absolutely and certainly.

**Comment by akre54** [comment]
Very cool. Thanks for putting in the work!

The purpose of the "rest" parameter is to allow a function to take a variable number of arguments, rather than constrain you to defining the arguments the function supports upfront. The function's named arguments are assigned to variables as usual, while the rest of the arguments are stored in an array.

In ES2015 (aka ES6) you might write:

```js
const func = (a, b, ...others) => {
  return a + b + process(others)
}

func(1, 2, 3, 4, 5)
```

Here `a` would be `1`, `b` would be `2`, and `others` would be `[3, 4, 5]`. 

In Underscore this works similarly:

```js
_.restArgs(function(a, b, others) {
  return a + b + process(others)
})
```

If you're familiar with ES5, it's equivalent to writing something like `var others = [].slice.call(arguments, 2)`.

We use it to achieve the same effect as ES2015 in plain ES5 code (`invoke`, `pick`, `zip`, `without`, `union`, and `difference` are a couple examples.)

> BTW, Underscore is under MIT license right?

Yep yep. Have at it.

**Comment by hushPlease** [comment]
Thanks a lot!
Very helpful and comprehensible cases.
