### ISSUE TITLE
_.max and _.min return Infinity on empty arrays

### ISSUE THREAD

**Issue by ghiculescu** [jashkenas/underscore#2646]
underscore 1.8.3 - i ran these in dev tools on http://underscorejs.org/# in Chrome

```
_.max([])
> -Infinity
_.min([])
> Infinity
```

i would expect it to return `null`, `undefined`, or something similar.

ruby `[].max` returns `nil`, lodash `_.max([])` returns `undefined`.

`Math.max()` returns `Infinity` too so I appreciate that's probably what's causing this, but it seems like a dumb behaviour.

**Comment by pnowak** [comment]
This behavior isn't so stupid.
The purpose of this function (_.max()) and static method (Math.max()) is return the largest of the resulting values. When no arguments are given, the result is -Infinity, because it is the value of which is based on a comparison. 
And similarly in _.min() (and Math.min()) and value Infinity - returns the smallest of the resulting values based on Infinity.

**Comment by captbaritone** [comment]
I agree it's not 100% obvious what you would get in those cases, but I don't think the existing behavior is unreasonable. Also, this behavior is explicitly called out in the docs.

**Comment by allenbriggs** [comment]
I agree with you @ghiculescu.  We are dealing with max/min value of a property in a list.  If there are no max/min values then return `null` or `undefined`.  The returned `Infinity` values are not useful and require more work to handle (in almost every case).  There is no reason to overly optimize the return value before we get it back..
