### ISSUE TITLE
Potential Security Issue with trusting ".length"

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/underscore#2663]
This just came in over the transom:

> Howdy,

> We just had this report come into the node security report mailbox and I wanted to make sure to pass it along to the maintainers.

> Name: Potential DOS when using lodash/underscore on user-provided JSON

> Description: Lodash/underscore special treatment of objects with "length" attributes leads to possible DOS if _.each is used on user inputs. E.g. https://gist.github.com/syrnick/f1eed31db3de3a3466213150b05e34c6 .

> It appears that if length is provided in the object it causes some confusion with iteration. While the user has to be doing something that would cause an OOM (not directly tied to the additional iterations).

> Seems like something that many people would trip up on, not removing length before passing it in each.

> Thoughts?

```javascript
var _ = require('underscore');
// Assume user can send us JSON. E.g. we accept Content-type: application/json
var obj = {"keyFoo": "bar", "length": 1000000000};
var badKeys = [];
// Lets validate user keys:
_.each(obj, (v,k) => /^key/.test(k) || badKeys.push(k));

// expected
// badKeys is ["length"]
// actual
// crash with OOM
```

What do y'all think?

**Comment by akre54** [comment]
This is the old argument about splitting out `_.each` into an array-like and object keys / values version, right?

FWIW `Array.prototype.forEach` behaves similarly when called with this object, we just happen to switch based on the numeric length property.

**Comment by captbaritone** [comment]
Here is @jdalton's response regarding Lodash: https://medium.com/@jdalton/the-collection-methods-have-existed-in-underscore-since-its-start-in-2009-504833489ed4#.btc4p9qpg

Looks like jQuery is "vulnerable" to a similar kind of attack. The only difference being they do a little sanity check to make sure the final value exists `in` the array-like object.

```JavaScript
$.each({length: 40, 39: null}, () => console.log('here'));
// 40 "here"s are logged.
```

@akre54 I wasn't able to reproduce this behavior with `Array.prototype.forEach`. I tried the following and the callback seems to be called only once. Maybe you were referring to something else?

```JavaScript
Array.prototype.forEach.call({39: null, length: 40}, () => console.log('here'));
// "here" is logged.
```

I can't personally think of any way to handle "array-like" objects and simultaneously guard against this sort of attack, without adding a hugely expensive `in` check to every iteration.

**Comment by jdalton** [comment]
@captbaritone
`Array#forEach` skips holes in arrays though it still checks for the. I expanded my reply in medium with an example. I was pinged a few weeks ago by one of the Node Security folks to give them the run down. It's a non-issue.

**Comment by captbaritone** [comment]
Got it. I agree that we can close this issue.
