### ISSUE TITLE
Uncaught TypeError: Cannot read property '_' of undefined

### ISSUE THREAD

**Issue by wzup** [jashkenas/underscore#2680]
When I try to import the library into my ReactJS app, I get this error:

> underscore.js:15  Uncaught TypeError: Cannot read property '_' of undefined

The error is thrown here. `root` is `undefined`.
```
(function() {

  // Baseline setup
  // --------------

  // Establish the root object, `window` in the browser, or `exports` on the server.
  var root = this;

  // Save the previous value of the `_` variable.
  var previousUnderscore = root._; // <==  !!! HERE !!!

  // Save bytes in the minified (but not gzipped) version:
  var ArrayProto = Array.prototype, ObjProto = Object.prototype, FuncProto = Function.prototype;
```

Why does it happen? How to solve?

**Comment by bjmiller** [comment]
If you're transpiling with babel, or using `"use strict"`, the value of this will always be set to undefined, which is why `root` is undefined.  You need to do this differently.  This is not a problem with underscore.

**Comment by filips123** [comment]
@bjmiller I have the same problem. I am using [AEgir](https://www.npmjs.com/package/aegir) to build my project for the browser (with Webpack). This project is required by [Web3](https://github.com/ethereum/web3.js) and it causes the error. How can I fix this?

**Comment by nestoremgi** [comment]
I´m using a dependency called openpay.js which uses underscore.js like internal dependency   i dont know why next js is  complaining about this  error node_modules/underscore/underscore.js (15:32) @ _
- error Error [TypeError]: Cannot read properties of undefined (reading '_')
    at eval (webpack-internal:///(sc_server)/./node_modules/underscore/underscore.js:12:35)
    at eval (webpack-internal:///(sc_server)/./node_modules/underscore/underscore.js:1171:4) and it´s strange because im using same library on an Astro project and it works without problems could it  be  related with ts config?

**Comment by jgonggrijp** [comment]
@nestoremgi The problem might be present only with particular combinations of versions of openpay and underscore, so as a first stop, you could check whether you are using the same version in both projects. If not, try the version from the Astro project.

Otherwise, your best bet is a question on stack overflow, because this problem is probably not inherent to underscore but rather due to a bad interplay between multiple libraries and tools. If you go that route, make sure to include a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
