### ISSUE TITLE
Missing mapcan function.

### ISSUE THREAD

**Issue by mafiosso** [jashkenas/underscore#2771]
In many cases I need to map some list/array and remove some subset of original items. In Common Lisp there exists useful procedure mapcan which shortens list if iteratee return nil. I suggest simple implementation for underscore:

```javascript
_.mapcan = function(arr, fn, ctx){
  return _.filter( _.map(arr, fn, ctx),
    function(item){
      if( item === undefined )
        return false;
      return true;
  });
};
```

**Comment by milad1367** [comment]
Hi, if you want I can fix it .

**Comment by mafiosso** [comment]
It will make me happy :+1:

**Comment by jgonggrijp** [comment]
This can be implemented in less code, and added to Underscore with chaining support, as follows:

```js
function mapcan(collection, iteratee, context) {
    return _.chain(collection).map(iteratee, context)
        .filter(_.negate(isUndefined)).value();
}

_.mixin({mapcan: mapcan});
```

Since it's quite obscure, I think this belongs in [underscore-contrib](https://github.com/documentcloud/underscore-contrib) instead. It has been unmaintained for a while, but I'm looking into a solution for that. If you submit a pull request over there, it might not be merged but it will be noticed.

**Comment by mafiosso** [comment]
I tried to clone underscore-contrib and add mapcan code but without luck. Grunt is broken in current node v14.4.0, dependencies are pretty outdated. Does it make any sense to resurrect underscore-contrib?

**Comment by jgonggrijp** [comment]
Hey @mafiosso, thanks for getting back here. I think it makes total sense to resurrect Underscore-contrib and in fact, I'm planning to do exactly that. If you want, you are welcome to help me with that, but I take no offense if you don't.

As for your prospective PR to add `mapcan`, you could start by pushing a branch that just adds the function to the code, ignoring the infrastructure for the moment. You or somebody else could then later brush up that branch when contrib is ready to receive PRs again.

**Comment by mafiosso** [comment]
Hi @jgonggrijp, sorry for my previous unreachability. Yes I agree with you - underscore-contrib is full of fine utilities, it would be a shame to get rid of this project. I can help you with update of this project eventually. Maybe you should tell me your vision first.

Does it make a sense to make the pull request before the planned "great" undescore-contrib update?

**Comment by jgonggrijp** [comment]
> Yes I agree with you - underscore-contrib is full of fine utilities, it would be a shame to get rid of this project.

Good to have you on board!

> I can help you with update of this project eventually. Maybe you should tell me your vision first.

My ultimate plan is to modularize it all the way down to the individual functions, with a similar layout as I have made for Underscore itself (see the master branch). @fogus agreed with this plan in private communication, so I foresee no major hurdles except for the nontrivial amount of work.

Before I can make any exciting changes, though, I'll need to tackle boring issues like the outdated dependencies that you mentioned. I don't really have any particular plan for that, it's just fixing things until everything is smooth again. So, in stages:

1. Fix things so that development is smooth again.
2. Check existing issues and PRs for things that might be best addressed before modularization.
3. Release version 0.4.
4. Modularize.
5. Release version 0.5.
6. Complete any missing documentation and unittests.
7. Release version 1.0.

You are welcome to step in at any stage and I'll happily review anything you submit.

> 
> Does it make a sense to make the pull request before the planned "great" undescore-contrib update?

If you mean to be actively involved in the update, or if you don't mind waiting, then it is most efficient for both of us if you wait with your `mapcan` contribution until after stage 4. Otherwise, it makes perfect sense to make the pull request as soon as it suits you. You can mark it as a draft to indicate that it isn't ready for merging.

**Comment by jgonggrijp** [comment]
> Ok I check current possibilities to get Grunt working in short time.

Great!

> Maybe we should communicate via some new issue in underscore-contrib next time to not clutter up underscore.

I don't think it hurts to have this discussion here, but you are right that discussion about Contrib belongs over there. Especially so that it does not escape the attention of anyone interested in that repository. I guess I should put the plan that I outlined above over there as well. I'll hold off doing that until I'm actually ready to get started, though. Right now, I first want to get Underscore 1.11 ready to release.

I created a new "contrib" label to identify issues like this one. I'm closing this one to clarify that it is not something that needs to be done about Underscore itself, but you can still respond if you feel like it.
