### ISSUE TITLE
_.escape test suit

### ISSUE THREAD

**Issue by lucky06688** [jashkenas/underscore#2794]
// handles multiple escape characters at once
    var joiner = ' other stuff ';
    var allEscaped = escapeCharacters.join(joiner);
    allEscaped += allEscaped;
    **assert.ok(_.every(escapeCharacters, function(escapeChar) {
      return allEscaped.indexOf(escapeChar) !== -1;
    }), 'handles multiple characters');**
    assert.ok(allEscaped.indexOf(joiner) >= 0, 'can escape multiple escape characters at the same time');

I can't understand this test in which the 'allEscaped' is not escaped. https://github.com/jashkenas/underscore/blob/v1.9.0/test/utility.js#L142-L14

**Comment by jgonggrijp** [comment]
@lucky06688 Thanks for reporting. It appears indeed that `allEscaped` is never used to actually test the behaviour of `_.escape` and `_.unescape`. This is still an issue on master:

https://github.com/jashkenas/underscore/blob/2a932470303157072015d5ab7f26d40b9deb4634/test/utility.js#L162-L169

It appears this has always been the case since these lines were first added in 9c1c3ea4fcafe82d546e190c5f0edd02940808e5. The author probably forgot.
