### ISSUE TITLE
package.json needs type module for ESM exports to work in node 13+?

### ISSUE THREAD

**Issue by PeterKnight** [jashkenas/underscore#2874]
Since upgrading Node to v13 I'm having trouble importing modules from underscore unless I add `"type": "module"` to underscore's package.json.

**Comment by jgonggrijp** [comment]
Thanks @PeterKnight for reaching out.

Please provide some details:

- version of Underscore
- code example of your ESM imports
- any additional tools that you're using, including versions
- configuration code for your tools

Our continuous integration tests [run fine on node 14](https://travis-ci.org/github/jashkenas/underscore/jobs/722135280), so at least it cannot be the case that there is an overall compatibility issue.

**Comment by jgonggrijp** [comment]
Oh, and also the error message(s) you're seeing.

**Comment by PeterKnight** [comment]
Code example:
`import { without } from "underscore/modules/index.js";`

Version of underscore 1.11.0

Tested on Node v13.11 and again on Node v14.8.0.
On Node v13 the error mentions not finding an export called `without`
Retested after updating to Node v14.8.0 which gives a more relevant error message:

```
import { without } from "underscore/modules/index.js";
         ^^^^^^^
SyntaxError: The requested module 'underscore/modules/index.js' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'underscore/modules/index.js';
const { without } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Adding `"type": "module" to underscore's package.json fixes the issue.

Let me know if I need to provide more details!

**Comment by jgonggrijp** [comment]
That's enough to confirm my suspicion, thank you.

My suspicion was that you were using Node.js's builtin, experimental support for ESM, which we don't support. As you say, it doesn't work "out of the box"; it requires either that we set the `type` to `module` (which breaks the package for the rest of the world), or that we add an `exports` field (which will basically prevent us from being compatible with everyone we want to be compatible with at the same time), or that we use the `.mjs` extension for our ES modules. The latter would be an option for us in principle, but since it comes with rather harsh restrictions as well and Node.js's builtin ESM support is still subject to change, I have opted out of it completely for the time being.

Frankly, the experimental ESM support in Node.js is quite a pain at this time. I hope that they will make it much less intrusive in the future. See the [official documentation](https://nodejs.org/api/esm.html) and [my mention of it](https://juliangonggrijp.com/article/introducing-modular-underscore.html#what-about-.mjs) in the article I wrote about the new modules feature.

There is good news, though: you can make it work without having to change your code. Just use the [esm loader](https://www.npmjs.com/package/esm) and everything will work fine. Pretend to Node.js that you're using CommonJS for best results (so use the `.js` extension instead of `.mjs` and don't use the `--input-type` flag).

By the way, as of version 1.11, each function can be imported from a separate module for better selectivity:

```js
import without from 'underscore/modules/without.js';
```

I recommend using modular imports specifically to compose a custom Underscore-like interface, and using monolithic imports, from either standard Underscore or your own customized Underscore, everywhere else. [The article](https://juliangonggrijp.com/article/introducing-modular-underscore.html) discusses all the ins and outs of monolithic vs. modular imports and customization. I also wrote a [TLDR version](https://twitter.com/juliangonggrijp/status/1299478223760306176) on Twitter.

I'll close this issue now, but questions and comments are still welcome.

**Comment by PeterKnight** [comment]
Thank you for the thorough explanation @jgonggrijp. It's definitely frustrating how Node is handling modules, the .mjs file extension stuff is particularly grating. I had working code with the esm package when things suddenly broke and I started having trouble importing from esm modules. Then I tried removing esm since I discovered Node now supports esm modules without a flag, but I just ran into issues with the imports of different dependencies. I'll see if I can get things working with the esm package enabled again.

**Comment by jgonggrijp** [comment]
Welcome. Sorry to hear the esm package did not address your needs. I'd be happy to take a look at your setup if you'd like some help.

**Comment by PeterKnight** [comment]
Thanks for the offer of help, I think I've finally got things working again after refactoring code, so the esm package is doing the trick again. And also thank you for making underscore support esm imports in the first place!

**Comment by jgonggrijp** [comment]
Welcome again and glad to hear it's working now!
