### ISSUE TITLE
Adding methods IsDefined and isNotNull

### ISSUE THREAD

**Issue by marcolin94** [jashkenas/underscore#2893]
Hi guys,

Currently if you want to check that an element is non-null or necessary you have to use the two methods in this way:
- !(isNull(...))
- !(isUndefined(...))

It would be useful for code cleanup to have these two methods directly

- isNotNull(...)
- isDefined(...)

What do you think?
Thanks a lot

**Comment by jgonggrijp** [comment]
You can add each of them to Underscore with a single line if you need to:

```js
import _, { mixin, negate, isNull, isUndefined } from 'underscore';

mixin({
    isNotNull: negate(isNull),
    isDefined: negate(isUndefined)
});

_.isDefined({}); // true
```

Generally, in order to keep Underscore lean and mean, we don't add functions that are just simple negations, compositions etcetera of other functions that are already in Underscore. However, please feel welcome to submit a PR to [Underscore-contrib](https://github.com/documentcloud/underscore-contrib) if you still think it should be exported from somewhere.
