### ISSUE TITLE
Why put the compiled .js file in the source code?

### ISSUE THREAD

**Issue by 368573607** [jashkenas/underscore#2905]
Shouldn't it only provide source code?

**Comment by jgonggrijp** [comment]
Because this is an easy way for us to offer a bleeding-edge download on [the website](https://underscorejs.org).

Note that the bundles are generated in a commit hook, so the developer doesn't have to remember to commit the bundle, as long as she makes sure to install the dev dependencies.

Also, a subtle but important difference: "in the repository" is not the same as "in the source". The source is exclusively in the `modules/` directory of the repository. Consider everything outside of that directory as website-, packaging- or testing-related. The bundles are quite similar to the `index.html` and the `docs/` directory in this regard.

I consider your question answered, so I'm closing this, but please feel free to comment again if you have any more questions.
