### ISSUE TITLE
Alphabetize exports in underscore.js

### ISSUE THREAD

**Issue by saaasaab** [jashkenas/underscore#2989]
This is just a cleanup ticket to alphabetize the exports in the main underscore.js file,  leaving    
 **__proto__: null,**
at the top and     

**'default': _$1** 
at the bottom

![Group 870](https://github.com/jashkenas/underscore/assets/51898351/5e753437-0659-4ffb-8c4e-2e4a0ac608f6)

**Comment by jgonggrijp** [comment]
@saaasaab the `underscore.js` is generated by Rollup in a commit hook, so your changes would be destroyed on the next commit.

The order is determined by the content of `modules/index.js`. That order has been carefully chosen in order to make the [single read annotated source](https://underscorejs.org/docs/underscore-esm.html) as readable as possible.

Why would you prefer the exports to be sorted alphabetically?

**Comment by saaasaab** [comment]
Thank you for explaining that.  The reason I thought it was good for the exports to be alphabetical is mainly so it is easier to find what you're looking for when going through the code. Again, thank you for going though over the process.
