### ISSUE TITLE
Mention _.VERSION in the documentation

### ISSUE THREAD

**Issue by clanceyp** [jashkenas/underscore#2992]
Add an alias, or method, for VERSION const e.g. '_.UNDERSCORE_VERSION' or _.version() ==> "Underscore v.X.XX.X" to allow users to determine if Underscore is being used and if so which version.

**Comment by jgonggrijp** [comment]
@clanceyp It is already accessible as `_.VERSION`. I now realize it isn't mentioned in the documentation, though. Will label and retitle accordingly. Thanks for bringing it up!

**Comment by clanceyp** [comment]
What I want to know is whether it's the Underscore library or a different library using the "_" character alias.

**Comment by jgonggrijp** [comment]
Are you aware of other libraries than Underscore or Lodash that use `_`?

If you only need to distinguish between those two, you can use feature detection. Lodash has `_.partialRight`, Underscore does not. Underscore has `_.restArguments`, Lodash does not (at least not in version 4+). There are many other differences as well.

Also, if the major version number is 1, you are much more likely dealing with Underscore than Lodash, since Lodash is currently at 4.
