### ISSUE TITLE
_.sortBy should perfrom a stable sort.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#738]
_.sortBy should perfrom a [stable](http://en.wikipedia.org/wiki/Sorting_algorithm#Stability) sort in IE > 8, Opera, and V8.

``` js
function Pair(x, y) {
  this.x = x;
  this.y = y;
}

var collection = [
  new Pair(1, 1), new Pair(1, 2),
  new Pair(1, 3), new Pair(1, 4),
  new Pair(1, 5), new Pair(1, 6),
  new Pair(2, 1), new Pair(2, 2),
  new Pair(2, 3), new Pair(2, 4),
  new Pair(2, 5), new Pair(2, 6)
];

var actual = _.sortBy(collection, function(pair) {
  return pair.x;
});

deepEqual(actual, collection);
```

**Comment by olleicua** [comment]
Am I missing something here?  it looks like the following would be unstable:

```
_.sortBy([
  { x: 1 },
  { x: 2 }
], 'y')
```

Because the `y` property is undefined it looks like the result will depend on what order the native `.sort` method compares them in.

**Comment by jdalton** [comment]
> Stable sorting algorithms maintain the relative order of records with equal keys (i.e. values). That is, a sorting algorithm is stable if whenever there are two records R and S with the same key and with R appearing before S in the original list, R will appear before S in the sorted list.

It should be stable.

Running in Underscore:
```js
_.sortBy([
  { x: 1 },
  { x: 2 },
  { x: 3 },
  { x: 4 },
  { x: 5 }
], 'y')
// => [{"x":1},{"x":2},{"x":3},{"x":4},{"x":5}]
```
Even running in different sort order (Lodash):
```js
_.orderBy([
  { x: 1 },
  { x: 2 },
  { x: 3 },
  { x: 4 },
  { x: 5 }
], 'y', 'desc')
// =>[{"x":1},{"x":2},{"x":3},{"x":4},{"x":5}]
```

If you find a bug though please file an issue.

**Comment by olleicua** [comment]
I'm still not convinced it would be reliably stable in every JavaScript implementation.  Why is the case where the keys are undefined different from the case where the keys are equal?  [According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) native `.sort` isn't necessarily stable.

I don't have access to any JavaScript implementations where `.sort` isn't stable because according to [this](http://stackoverflow.com/questions/3026281/array-sort-sorting-stability-in-different-browsers) they are all super old.  That does mean this won't come up very often but if we are going to bother to make `_.sort` stable we should do it right.

**Comment by jdalton** [comment]
>  According to MDN native .sort isn't necessarily stable.

Yep, which is why Underscore / Lodash do extra work to make it stable.

**Comment by olleicua** [comment]
So the only sufficiently old browser I could get working was IE5 for Mac which inconveniently was unable to load Underscore 1.8.3 (and because of IE5 for Mac's complete lack of developer tools I'm not sure why).

I was able to demonstrate the bug by stubbing out an unstable version of `.sort` in ChromeOS v48 with Underscore 1.8.3:

```javascript
> var sort = Array.prototype.sort;
> Array.prototype.sort = function(fn) { return sort.call(this, function(a, b) { return fn(b, a); }); };
> _.sortBy([ { x: 1 }, { x: 2 }, { x: 3 } ], 'y');
[{"x": 3}, {"x": 2}, {"x": 1}]
```

I'll open an issue and make a PR tomorrow.

**Comment by jdalton** [comment]
Don't bother with the PR.
IE5 for mac isn't realistic it's 2016.

We have tests for unstable sorting.
You don't need to pave `Array#sort` to see it in modern environments. In Chrome just try
```js
[1,2,3,4,5,6,7,8,9,10,11].sort(function(){return 0;})
// => [6, 1, 3, 4, 5, 2, 7, 8, 9, 10, 11]  // unstable

[1,2,3,4,5,6,7,8,9,10].sort(function(){return 0;})
// => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] // stable
```

**Comment by olleicua** [comment]
Oh wow, nevermind not a bug I just realized.
