### ISSUE TITLE
_.template couldn't used in mozilla mobile platform

### ISSUE THREAD

**Issue by sandhua** [jashkenas/underscore#941]
Mozilla said:
Function constructor, similar to eval() is disabled by content security policy.

will underscore update for it?

thanks!

**Comment by Poorchop** [comment]
@braddunbar can you elaborate a little more for the clueless like me? All I know is that the source property returns the text of the regular expression, but I'm not sure how to use this for my purposes.

I am basically just interesting in overwriting the _.template() function to play nicely with CSP. This way I can still use ` _.template("<%= replaceMe %>", ...)` in my JavaScript files instead of using my custom global function (which achieves a similar result). This way, my project has some consistency and anyone viewing the source code will be less confused when they see the familiar _.template() function instead of my weird custom function.

**Comment by megawac** [comment]
Hi @Poorchop, the most common way to do this step currently is via [`grunt`](https://github.com/gruntjs/grunt-contrib-jst), [`gulp`](https://www.npmjs.com/package/gulp-jst) or [`browserify`](https://github.com/zertosh/jstify) (to my knowledge).

**Comment by Poorchop** [comment]
Thank you for the links.
